port:
  3000
cookie:
  secret: "cookiesecret"
session:
  secret: "sessionsecret"
mongodb:
  host: "localhost"
  db: "hatebu_offkai"
hatena:
  consumerKey: "..."
  consumerSecret: "..."
  callbackURL: "http://localhost:3000/auth/hatena/callback"
